### ISSUE TITLE
Test gives SyntaxError

### ISSUE THREAD

**Issue by tukoz** [rmiceli/rsnapstats#1]
Hi, looks nice. Is there any additional parameters to pass to, eg rsync, via rsnapshot.conf? 

Makes a syntax error in this location (see config below), whether launched by hand or via cron:

rsnapshot -c /etc/rsnapshot.conf daily 2>&1 | python /root/scripts/backup/rsnapstats.py 2>&1 | mail -s"SUBJECT" lliseil

```
 File "/root/scripts/backup/rsnapstats.py", line 55
    (1<<50L, 'PB'),
          ^
SyntaxError: invalid syntax
```

Which is then sent by Email.

Config:
arch linux (Linux 3.18.7-2-ck x86_64)
python 3.4.2 - rsync 3.1.1 - rsnapshot 1.3.1 (working) - msmtp

**Comment by rmiceli** [comment]
Thanks for the feedback. The script was written for python2. In python3, all integers are treated as long, so the L is invaild. 

I will try to fix this soon. There will likely be issues with the print statements as well. If you have python2 installed, you should try using that in the mean time.

**Comment by tukoz** [comment]
Using `...python2 /path/to/rsnapstats.py...` gives the awaited nicely detailed reports (I didnt try out using eg 'python2.7').
Excuse the delay; rsnaphot _Verbose level_ was on 2 (I saw 3... but that was the _Log_ level as I overlooked the conf file).
Thanks, rmicelli.
