### ISSUE TITLE
Not working in Debian

### ISSUE THREAD

**Issue by MartinAyla** [rmiceli/rsnapstats#2]
Hi

This tool looks really useful, but I can't get it to work in Debian 8.

It only prints the Error lines, none of the transfer stats.

I'm using rsnapshot 1.3.1-7 and rsync 3.1.1.

**Comment by rmiceli** [comment]
Thanks for using this script.

What errors does it print? Which version of python are you using? You might need to call the script with python2 because it does not work for python3 yet.

**Comment by MartinAyla** [comment]
Thanks for the reply.

I'm using Python 2.7.9.

It doesn't print any errors. What I mean by 'Error lines' above is that it prints any lines with 'Error' in them from the rsync log. But the rest of the script doesn't work for me, meaning no stats are printed.

**Comment by rmiceli** [comment]
Okay. I'm using rsnapshot 1.3.1-4 on debian 8. The rest of my setup is the same. I will try to investigate this issue

**Comment by MartinAyla** [comment]
I use 'rsnapshot sync' if that makes a difference?

```
/usr/bin/rsnapshot -c /etc/rsnapshot_test.conf sync 2>&1 | /home/martin/rsnapstats.py | mail -s "test"
```

**Comment by MartinAyla** [comment]
It works now.

I had to add the python declaration to the top of the script:

```
#!/usr/bin/python
```

And use this command:

```
sudo /usr/bin/rsnapshot -c /etc/rsnapshot_test.conf sync 2>&1 | sudo tee -a /var/log/rsnapshot_test.log | rsnapstats.py 2>&1 | mail -s "rsnapshot_test" MY_EMAIL && sudo /usr/bin/rsnapshot -c /etc/rsnapshot_test.conf daily
```
