### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by VARGA-Peter** [rmiceli/rsnapstats#3]
[output.txt](https://github.com/rmiceli/rsnapstats/files/1692252/output.txt)

This error is thrown with the attached output.txt

```
Traceback (most recent call last):
  File "/usr/local/bin/rsnapstats.py", line 140, in <module>
    main()
  File "/usr/local/bin/rsnapstats.py", line 99, in main
    stats_dict['source'] = line.split()[-2].split('@')[-1]
IndexError: list index out of range
```

Python 2.7.13
SLES 12 SP3

```
rsync  version 3.1.0  protocol version 31
Copyright (C) 1996-2013 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes, prealloc, SLP

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
```
Other directories work fine but they don't have any file with the string "source" inside. Can it that it is parsing also the filenames instead of the summary?

**Comment by rmiceli** [comment]
Thanks for issue ticket. I just pushed a fix for your use case in commit 2273b3fbf6cede8fb1716accfdcecb65c1361483. Let me know if it works for you now. 

However, this doesn't fix the larger issue that you point out. The code is still parsing the filenames instead of the summary. For example, if someone has a file with "bytes/sec" in the string, the code will fail. I will have to think of a better solution.

**Comment by VARGA-Peter** [comment]
Yes, this fixed the problem. **THANK YOU**

Anyway, it is not your fault that it does not work. I was reviewing the source code of `rsnapshot `and I think the problem is that `rsnapshot `is always adding the `v` flag which displayes the filenames.

Without this flag your report would work because the `--stat` flag displays only the needed statistic,

**Comment by VARGA-Peter** [comment]
Sorry, it does not work. It displays always the first server. Attached you find simplified the `rsync `output. You can see that the first entry is displayed twice `AAEB-APP206LY:/etc/`

The 2nd server/path `AAEB-APP206LY:/application/` is missing in your output.

```
AAEB-BKP-NFS216LX:/.snapshots # rsnapshot daily 2>&1 | python rsnapstats.py
core/resources/iban/docs/COMEDY-OF-ERRORS

AAEB-APP206LY:/etc/
         files backed-up: 12503 (82.10 MB)
         files updated: 11031 (82.10 MB)
         sent/received: 213.30 kB / 82.87 MB
         transfer rate: 18.46 MB/sec
         speedup: 0.99
AAEB-APP206LY:/etc/
         files backed-up: 12503 (82.10 MB)
         files updated: 11031 (82.10 MB)
         sent/received: 213.30 kB / 82.87 MB
         transfer rate: 18.46 MB/sec
         speedup: 0.99
```
[output.txt](https://github.com/rmiceli/rsnapstats/files/1692312/output.txt)

**Comment by VARGA-Peter** [comment]
OK. I could hack the source of `rsnapshot `and commented these lines:

```
if ($verbose > 3) { $local_rsync_short_args .= 'v'; }
if ($verbose > 3) { $rsync_short_args .= 'v'; }
```

Now the synchronized files are **NOT** displayed anymore but your script has still the bug the only the 1st synchronized server/path is displayed.

Attached you find now the nice output with which you can work in order to fix the issue.

Also, the output from your program is now better:
```
AAEB-BKP-NFS216LX:/.snapshots # rsnapshot daily 2>&1 | python rsnapstats.py
AAEB-APP206LY:/etc/
         files backed-up: 12503 (82.10 MB)
         files updated: 11031 (82.10 MB)
         sent/received: 213.20 kB / 82.87 MB
         transfer rate: 33.23 MB/sec
         speedup: 0.99
AAEB-APP206LY:/etc/
         files backed-up: 12503 (82.10 MB)
         files updated: 11031 (82.10 MB)
         sent/received: 213.20 kB / 82.87 MB
         transfer rate: 33.23 MB/sec
         speedup: 0.99
```

When you compare it with the previous post you will see the line `core/resources/iban/docs/COMEDY-OF-ERRORS` is now missing because no files are displayed which can confuse your program.

THANK YOU a lot!

[output.txt](https://github.com/rmiceli/rsnapstats/files/1692317/output.txt)

**Comment by rmiceli** [comment]
Thanks for your help. You provided a better set of output files to test against. 

Try the latest code in 7691a046bcde4b1a648f4d4ca5251756aaaef7b8. This still parses all the file names if the user does not hack the rsnapshot source, but it should work for now. I'll start a new branch and try some other solutions to ignore the -v output from rsync.

**Comment by VARGA-Peter** [comment]
YEP! Now it works!

I appreciate your very fast support! I will write the `rsnapshot `developer team if they can suppress the built-in `v` flag for the `rsync `command.

**Comment by VARGA-Peter** [comment]
Once you start a new branch, could you consider to add a thousand separator character to the output? `rsync `is displaying all values with a thousand separator character.

**Comment by rmiceli** [comment]
Will do. I started a new issue for that: #4
