### ISSUE TITLE
Not working in Debain 9

### ISSUE THREAD

**Issue by zyrixx** [rmiceli/rsnapstats#6]
I've installed rsnapsstats for guidance and it just does not work. Also the hint, in the first line
#! /usr/bin/python 

did not succeed. 

  Installiert:           1.4.2-1
  Installationskandidat: 1.4.2-1
  Versionstabelle. *** 1.4.2-1 500
rsync:
  Installiert:           3.1.2-1+deb9u1
  Installationskandidat: 3.1.2-1+deb9u1
  Versionstabelle: *** 3.1.2-1+deb9u1 500

It is the same on other systems as well. The mail arrives, but the content is empty. What can you do? thanks for all

**Comment by rmiceli** [comment]
Can you post the specific error you receive when trying to run? Can you also post the output of `which python`? Thanks

**Comment by zyrixx** [comment]
No error, the Mail is empty. 

python:
  Installiert:           2.7.13-2
  Installationskandidat: 2.7.13-2
  Versionstabelle:
 *** 2.7.13-2 500
        500 http://ftp.de.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status

Here a few extracts from the rsnapshot.conf

#
cmd_cp          /bin/cp
#
verbose         3
#
rsync_short_args        -a
rsync_long_args         --delete --numeric-ids --relative --delete-excluded --stats

**Comment by rmiceli** [comment]
Got it, so the issue is with the crontab and not rsnapstats. These posts seem to offer a few work-arounds to fix the crontab: 

http://www.backupcentral.com/forum/18/47972/rsnapreport_sending_null_email_reports
http://www.backupcentral.com/forum/18/166127/rsnapreport_pl_is_sending_me_empty_email

**Comment by zyrixx** [comment]
No, that has nothing to do with the cron. When I do the following in the console:

rsnapshot daily 2>&1 | python /usr/local/bin/rsnapstats.py 2>&1 | mail -s "rsnapshot_test" email@domain.com


the mail also arrives empty.

**Comment by rmiceli** [comment]
Can you increase verbose to 4 in rsnapshot.conf and confirm if mail is still empty?

Does redirecting output to a file produce an empty file?
`rsnapshot daily 2>&1 | python /path/to/rsnapstats.py 2>&1 >> /var/log/rsnapshot.log`

**Comment by zyrixx** [comment]
Hallo, verbose  4 was the solution. Thanks for all.

**Comment by rmiceli** [comment]
Thanks for the feedback. I will update the Readme
